name: mrz_parser_esp
description: Parse MRZ (Machine Readable Zone) from identity documents. Enhanced support for Spanish IDs.
version: 1.0.0
homepage: https://github.com/mirabuenos/mrz_parser
environment:
  sdk: ">=2.12.0 <4.0.0"
dev_dependencies:
  collection: ^1.19.0
  test: ">=1.16.5 <2.0.0"
  very_good_analysis: ^6.0.0
